# Useful ref: https://docs.codecov.io/docs/commit-status
codecov:
  require_ci_to_pass: yes
  coverage:
    range: 70..100
    round: down
    precision: 2
    status:
      project:
        default: false  # disable the default status that measures entire project
        tests:  # declare a new status context "tests" with 100% coverage
          target: 100%
          paths: "tests/"
        app:  # declare a new status context "app" for everything else
          paths: "!tests/"
          target: auto
      patch:
        default:
          target: auto
          threshold: 0%
          base: auto 
          # advanced
          branches: 
            - master
          if_ci_failed: error #success, failure, error, ignore
          only_pulls: false
          flags: 
            - "unit"
          paths: 
            - "src"
        # changes: no # TODO decide if necessary

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
