version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Run ci.sh"
          command: source ci.sh


workflows:
  main:
    jobs:
      - test