version: 2.1

# orbs:
#   codecov: codecov/codecov@1.2.3

jobs:
  test:
    machine:
      image: ubuntu-2004:2024.05.1
    steps:
      - checkout:
          path: UBCRocketGroundStation
      - run:
          name: Install Java OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: "Run ci.sh"
          command: source ci.sh
          path: UBCRocketGroundStation
      - store_test_results:
          path: UBCRocketGroundStation/test_reports
      - store_artifacts:
          path: UBCRocketGroundStation/test_reports
      # - codecov/upload:
      #     token: $CODECOV_TOKEN
      #     file: 'UBCRocketGroundStation/coverage.xml'
      - run:
          name: Send unit tests to codecov
          command: |
            cd UBCRocketGroundStation
                  curl -Os https://cli.codecov.io/latest/linux/codecov
                  chmod +x codecov
                  ./codecov do-upload -s test_coverage
            cd ..

workflows:
  main:
    jobs:
      - test