version: 2.1

orbs:
  codecov: codecov/codecov@1.2.3

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: UBCRocketGroundStation
      - run:
          name: "Run ci.sh (setup)"
          command: source ci.sh
          path: UBCRocketGroundStation
      - store_artifacts:
          path: UBCRocketGroundStation
          destination: coverage.xml
      - codecov/upload:
          token: $CODECOV_TOKEN
          file: 'UBCRocketGroundStation/coverage.xml'

workflows:
  main:
    jobs:
      - test