version: 2.1

orbs:
  codecov: codecov/codecov@1.2.3

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: UBCRocketGroundStation
      - run:
          name: "Run ci.sh"
          command: source ci.sh
          path: UBCRocketGroundStation
      - codecov/upload:
          file: coverage.xml

workflows:
  main:
    jobs:
      - test