name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5
    - name: Analysing the code with pylint
      run: |
        PYTHONFILES=""
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          if [[ -f $file && $file == *.py ]]
            then
              PYTHONFILES="${PYTHONFILES} $file"
            fi
        done
        echo $PYTHONFILES
        pylint $PYTHONFILES
